### ISSUE TITLE
Blinks on LEDs when receiving data from the PC app

### ISSUE THREAD

**Issue by danialonso** [LeoTechmaker/FollowersCounter#2]
There seems to be some problem in the source code. When the PC application is sending the data of the followers to the Arduino, the last leds of the panel have a strange flicker, increasing the luminosity in seconds in some LEDs of the last panel and part of the penultimate panel.

**Comment by Fardenco** [comment]
I can't replicate the issue.
It's strange, because all the LEDs are handled in the same way
To see if it's due to the software, you could plug a lcd on your arduino and modify the software to show the image it's sending to the LED array on the LCD.
You'll see if the pixel blinks on the LCD or not.
If not, you might have a faulty LED.
Because the ws2812b are transmitting data in chain, if one is faulty, I assume it could transmit wrong data to the next ones
